import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const font = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900", "300"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font} bg-[#191919] `}
      >
        <header>
          <Header/>
        </header>
        <main>
        {children}
        </main>
       <footer> 
           <Footer/>
      </footer>
      </body>
    </html>
  );
}
